### ISSUE TITLE
trk_pT selection

### ISSUE THREAD

**Issue by andresailer** [gaswk/FullSim#1]
I was wondering if I could figure out the plots about the "unexpected results" for the track reco,
And I stumbled over this line of code.

https://github.com/gaswk/FullSim/blob/a1b6c272da9d320cad340456ab368f7551ae1c88/TrackingPerformance/CLDperfPlot_track.py#L86

This is always true. Either replace the `or` by `and`, 
or simpler:
```python
  if trk_pT not in [0, -9]:  # Matched particles only
```
?

But actually track_pT is a list (isn't it?),
https://github.com/gaswk/FullSim/blob/a1b6c272da9d320cad340456ab368f7551ae1c88/TrackingPerformance/CLDperfPlot_track.py#L79
so something else should be checked?

**Comment by nitasad** [comment]
Thank you for the remark it should be `and` indeed.
I am not sure to understand your concern.
trk_pT is not a list but a vector.

**Comment by andresailer** [comment]
>  trk_pT is not a list but a vector.

Ok, but a vector will also never be equal to 0 or -9.

Don't you wan want to check `trk_pt`, i.e., `trk_pT[j]` the element of the vector?

**Comment by nitasad** [comment]
Ok I get it now, you are right!
